import { defaultSchema } from "rehype-sanitize";

// Sanitizer schema for the articles renderer only. It extends the default safe
// schema with the inline figure and SVG elements the Forensic Series plates
// use. Script, iframe, foreignObject, event handler attributes and unsafe URL
// schemes are not in the allowlist, so they are stripped.
const SVG_SHARED = [
  "fill",
  "fillOpacity",
  "fillRule",
  "stroke",
  "strokeOpacity",
  "strokeWidth",
  "strokeLinecap",
  "strokeLinejoin",
  "strokeDasharray",
  "opacity",
  "transform",
  "style",
  "className",
  "id",
];

export const articleFigureSchema = {
  ...defaultSchema,
  tagNames: [
    ...(defaultSchema.tagNames ?? []),
    "figure",
    "figcaption",
    "svg",
    "title",
    "desc",
    "path",
    "circle",
    "rect",
    "text",
    "tspan",
    "g",
    "line",
    "polyline",
    "polygon",
    "ellipse",
  ],
  attributes: {
    ...(defaultSchema.attributes ?? {}),
    figure: ["className", "id"],
    figcaption: ["className", "id"],
    svg: [
      "xmlns",
      "viewBox",
      "width",
      "height",
      "role",
      "preserveAspectRatio",
      "ariaLabel",
      "ariaHidden",
      ...SVG_SHARED,
    ],
    title: ["id"],
    desc: ["id"],
    g: [...SVG_SHARED],
    path: ["d", ...SVG_SHARED],
    circle: ["cx", "cy", "r", ...SVG_SHARED],
    ellipse: ["cx", "cy", "rx", "ry", ...SVG_SHARED],
    rect: ["x", "y", "width", "height", "rx", "ry", ...SVG_SHARED],
    line: ["x1", "y1", "x2", "y2", ...SVG_SHARED],
    polyline: ["points", ...SVG_SHARED],
    polygon: ["points", ...SVG_SHARED],
    text: [
      "x",
      "y",
      "dx",
      "dy",
      "fontFamily",
      "fontSize",
      "fontWeight",
      "fontStyle",
      "textAnchor",
      "letterSpacing",
      "dominantBaseline",
      ...SVG_SHARED,
    ],
    tspan: [
      "x",
      "y",
      "dx",
      "dy",
      "fontFamily",
      "fontSize",
      "fontWeight",
      "textAnchor",
      ...SVG_SHARED,
    ],
  },
};
