project_id = "bbmhrgpsyiahefnxqwfg"

[functions.notify-admin]
verify_jwt = false

[functions.scrape-clinical-trials]
verify_jwt = false

[functions.scrape-all]
verify_jwt = false

[functions.bundle-purchase-emails]
verify_jwt = false

[functions.posthog-analytics]
verify_jwt = false
