project_id = "bbmhrgpsyiahefnxqwfg"

[functions.notify-admin]
verify_jwt = false

[functions.scrape-clinical-trials]
verify_jwt = false

[functions.scrape-all]
verify_jwt = false

[functions.bundle-purchase-emails]
verify_jwt = false

[functions.posthog-analytics]
verify_jwt = false

[functions.upload-shopify-images]
verify_jwt = false

[functions.bundle-onboarding-email]
verify_jwt = false

[functions.inventory-sync]
verify_jwt = false

[functions.og-image]
verify_jwt = false

[functions.transcribe-voice]
verify_jwt = false

[functions.ping-sitemap]
verify_jwt = false

[functions.rate-limit-check]
verify_jwt = false

[functions.assess-score]
verify_jwt = false

[functions.share-assessment]
verify_jwt = false
