import { Navigation } from '@/components/Navigation';
import { Footer } from '@/components/Footer';
import { Helmet } from 'react-helmet';
import { Card } from '@/components/ui/card';
import { ExternalLink } from 'lucide-react';
import { Breadcrumb } from '@/components/Breadcrumb';

const Critiques = () => {
  return (
    <>
      <Helmet>
        <title>Critiques & Alternative Hypotheses | DMT Code</title>
        <meta 
          name="description" 
          content="Scientific counterarguments and alternative explanations for the Code of Reality phenomenon." 
        />
        <link rel="canonical" href="https://dmtcode.com/critiques" />
        <link rel="alternate" hrefLang="en" href="https://dmtcode.com/critiques" />
        <meta name="robots" content="index, follow" />
        <meta property="og:title" content="Critiques & Alternative Hypotheses | DMT Code" />
        <meta property="og:description" content="Scientific counterarguments and alternative explanations for the Code of Reality phenomenon." />
        <meta property="og:url" content="https://dmtcode.com/critiques" />
        <meta property="og:type" content="website" />
        <meta property="og:image" content="https://dmtcode.com/favicon.png" />
        <meta name="twitter:card" content="summary_large_image" />
        <meta name="twitter:url" content="https://dmtcode.com/critiques" />
        <meta name="twitter:title" content="Critiques & Alternative Hypotheses | DMT Code" />
        <meta name="twitter:description" content="Scientific counterarguments and alternative explanations for the Code of Reality phenomenon." />
        <meta name="twitter:image" content="https://dmtcode.com/favicon.png" />
        
        <script type="application/ld+json">
          {JSON.stringify({
            "@context": "https://schema.org",
            "@type": "WebPage",
            "headline": "Critical Perspectives - Skepticism & Ethics",
            "description": "Essays on methodological critiques, optical artifact explanations, and ethical concerns regarding 650 nm laser protocol research",
            "author": {
              "@type": "Organization",
              "name": "DMT Code Project"
            },
            "datePublished": "2025-11-29",
            "dateModified": "2025-11-29",
            "reviewedBy": {
              "@type": "Person",
              "name": "DMT Code Project Research Team",
              "jobTitle": "MSc Neuroscience"
            }
          })}
        </script>
        <script type="application/ld+json">
          {JSON.stringify({
            "@context": "https://schema.org",
            "@type": "BreadcrumbList",
            "itemListElement": [
              {
                "@type": "ListItem",
                "position": 1,
                "name": "Home",
                "item": "https://dmtcode.com/"
              },
              {
                "@type": "ListItem",
                "position": 2,
                "name": "Critiques",
                "item": "https://dmtcode.com/critiques"
              }
            ]
          })}
        </script>
      </Helmet>

      <div className="relative min-h-screen bg-background">
        <Navigation />
        <Breadcrumb />
        
        <main id="main-content" className="relative z-10 pt-4" role="main">

          <section className="container mx-auto px-4 py-16 max-w-4xl">
            <h1 className="text-4xl md:text-5xl font-bold mb-6">Critiques: the strongest cases against</h1>
            <p className="text-lg text-muted-foreground mb-10">
              The three most serious critical positions, each stated in its strongest form. Credit
              to Danny Goler as the originator of the reported observation. Publishing the strongest
              versions of the critiques is deliberate policy. If a claim cannot survive its best
              opponents, it does not deserve to survive.
            </p>

            <Card className="p-6 bg-primary/5 border-primary/20 mb-12">
              <p className="text-sm text-muted-foreground">
                <strong>Editorial note:</strong> nothing on this page asserts the reported DMT code
                is real, and nothing asserts it is fake. The purpose is to state the opposing cases
                cleanly so the registry data can be tested against them.
              </p>
            </Card>

            <Card className="p-8 bg-card border-border mb-8">
              <h2 className="text-2xl font-semibold mb-4">1) Laser speckle (Andrew Gallimore)</h2>
              <p className="text-base leading-relaxed mb-4">
                The diffracted 650 nm beam produces speckle, a physically real, structured optical
                pattern generated by interference of coherent light scattered from a rough surface.
                DMT amplifies pattern recognition. Under this account, the shared structure that
                observers report reflects shared optics rather than any external code being
                revealed.
              </p>
              <p className="text-base leading-relaxed">
                <strong>Testable prediction:</strong> swapping the diffraction grating for one with
                a different line density should change the reported forms in a way that tracks the
                new speckle field.
              </p>
            </Card>

            <Card className="p-8 bg-card border-border mb-8">
              <h2 className="text-2xl font-semibold mb-4">2) Cymatics (Andres Gomez Emilsson)</h2>
              <p className="text-base leading-relaxed mb-4">
                Non-linear standing-wave dynamics in visual cortex under DMT could generate
                structured, apparently discrete forms without any external code. On this view the
                laser is a source of visual noise, not a source of information, and the observed
                geometry is a signature of the visual system operating in a highly non-linear
                regime.
              </p>
              <p className="text-base leading-relaxed">
                <strong>Testable prediction:</strong> similar structured forms should appear given
                sufficient broadband visual noise, with or without a laser.
              </p>
            </Card>

            <Card className="p-8 bg-card border-border mb-8">
              <h2 className="text-2xl font-semibold mb-4">3) Cultural priming</h2>
              <p className="text-base leading-relaxed mb-4">
                Code and glyph imagery is culturally saturated. The Matrix, hieroglyphs, and
                digital-rain motifs are shared reference points, and expectancy is known to shape
                ambiguous perception. Under this account, observers who have read the literature
                see what they were primed to see.
              </p>
              <p className="text-base leading-relaxed">
                <strong>Testable prediction:</strong> naive observers who are not told what to
                expect should report different content from observers who have read the DMT code
                literature.
              </p>
            </Card>

            <Card className="p-8 bg-muted/30 border-border">
              <h3 className="text-xl font-semibold mb-4">Why this list matters</h3>
              <p className="text-base leading-relaxed">
                These predictions are testable, and the registry exists to accumulate the data that
                could distinguish them. Every symbol carries its metadata. Every source carries a
                stance score. Null results are published in the same place as confirmations. The
                point is not to win the argument. The point is to make the argument decidable.
              </p>
            </Card>

            <div className="mt-12 p-8 bg-muted/30 border border-border rounded-lg">
              <h2 className="text-2xl font-semibold mb-4">Related</h2>
              <div className="grid md:grid-cols-3 gap-4">
                <a href="/null-reports" className="text-gold hover:underline font-medium">
                  Null reports →
                </a>
                <a href="/registry" className="text-gold hover:underline font-medium">
                  Symbol registry →
                </a>
                <a href="/methods" className="text-gold hover:underline font-medium">
                  Methods →
                </a>
              </div>
              <p className="text-sm text-muted-foreground mt-6">Last updated: 2026-07-23</p>
            </div>
          </section>
        </main>

        <Footer />
      </div>
    </>
  );
};

export default Critiques;
