import { Navigation } from '@/components/Navigation';
import { Footer } from '@/components/Footer';
import { Helmet } from 'react-helmet';

const PERSON_LD = {
  "@context": "https://schema.org",
  "@type": "Person",
  "name": "Andrew Gallimore",
  "description":
    "Andrew Gallimore proposes the laser speckle explanation for the reported DMT code observation: that the diffracted 650 nm beam produces speckle, a physically real, structured optical pattern generated by interference of coherent light scattered from a rough surface, and that DMT amplifies pattern recognition applied to it.",
  "sameAs": ["https://alieninsect.substack.com/p/on-the-dmt-laser-code-of-reality"],
};

const BREADCRUMB_LD = {
  "@context": "https://schema.org",
  "@type": "BreadcrumbList",
  "itemListElement": [
    { "@type": "ListItem", position: 1, name: "Home", item: "https://dmtcode.com/" },
    { "@type": "ListItem", position: 2, name: "People", item: "https://dmtcode.com/people" },
    {
      "@type": "ListItem",
      position: 3,
      name: "Andrew Gallimore",
      item: "https://dmtcode.com/people/andrew-gallimore",
    },
  ],
};

const link =
  'text-primary underline underline-offset-4 decoration-primary/40 hover:decoration-primary transition-colors';

const PersonAndrewGallimore = () => {
  return (
    <>
      <Helmet>
        <title>Andrew Gallimore, the laser speckle critique | DMT Code</title>
        <meta
          name="description"
          content="Andrew Gallimore proposes the laser speckle explanation for the reported DMT code observation, one of the strongest cases against the reality-code reading."
        />
        <link rel="canonical" href="https://dmtcode.com/people/andrew-gallimore" />
        <meta name="robots" content="index, follow" />
        <script type="application/ld+json">{JSON.stringify(PERSON_LD)}</script>
        <script type="application/ld+json">{JSON.stringify(BREADCRUMB_LD)}</script>
      </Helmet>

      <div className="min-h-screen bg-background">
        <Navigation />

        <main className="px-4 sm:px-6 py-12 sm:py-16">
          <article className="mx-auto w-full max-w-[68ch]">
            <nav aria-label="Breadcrumb" className="mb-8 text-sm text-muted-foreground">
              <a href="/people" className="hover:text-foreground transition-colors py-2 inline-block">
                People
              </a>
            </nav>

            <h1 className="font-heading text-3xl sm:text-5xl font-bold tracking-tight text-foreground">
              Andrew Gallimore
            </h1>

            <div className="mt-8 space-y-6 text-base sm:text-lg leading-relaxed text-foreground/90">
              <p>
                Andrew Gallimore is one of the critics catalogued on this site's{' '}
                <a className={link} href="/critiques">
                  critiques page
                </a>
                , where the strongest cases against the reality-code reading are stated in their
                strongest form. His account is the laser speckle explanation, published as an essay
                and linked from that page.
              </p>

              <h2 className="font-heading text-xl sm:text-2xl font-semibold pt-6 text-foreground">
                The laser speckle explanation
              </h2>
              <p>
                The diffracted 650 nm beam produces speckle, a physically real, structured optical
                pattern generated by interference of coherent light scattered from a rough surface.
                DMT amplifies pattern recognition. Under this account, the shared structure that
                observers report reflects shared optics rather than any external code being
                revealed.
              </p>
              <p>
                <strong>Testable prediction:</strong> swapping the diffraction grating for one with
                a different line density should change the reported forms in a way that tracks the
                new speckle field.
              </p>

              <h2 className="font-heading text-xl sm:text-2xl font-semibold pt-6 text-foreground">
                Where this sits in the record
              </h2>
              <p>
                This site states the laser speckle account first among the alternatives to the
                reality-code reading, alongside cymatics and cultural priming, on both the{' '}
                <a className={link} href="/critiques">
                  critiques page
                </a>{' '}
                and the{' '}
                <a className={link} href="/protocol-guide">
                  protocol guide
                </a>
                . Independent controlled replication that isolates the 650 nm wavelength as a
                variable has not been published. That is a fact about the state of the field, not a
                charge against anyone.
              </p>

              <h2 className="font-heading text-xl sm:text-2xl font-semibold pt-6 text-foreground">
                Follow the record
              </h2>
              <ul className="list-disc pl-6 space-y-2">
                <li>
                  Read the essay:{' '}
                  <a
                    className={link}
                    href="https://alieninsect.substack.com/p/on-the-dmt-laser-code-of-reality"
                    rel="noopener"
                    target="_blank"
                  >
                    On the DMT laser code of reality
                  </a>
                </li>
                <li>
                  The <a className={link} href="/critiques">critiques page</a>, where the laser
                  speckle account is set alongside the other leading explanations
                </li>
                <li>
                  The <a className={link} href="/protocol-guide">650 nm laser protocol guide</a>
                </li>
              </ul>
            </div>
          </article>
        </main>

        <Footer />
      </div>
    </>
  );
};

export default PersonAndrewGallimore;
