-- Seed sample events (5 events) with correct event_type values
INSERT INTO public.events (title, description, event_date, event_type, location, organizer, url, is_approved, submitted_by) VALUES
('Psychedelics Today Conference 2026', 'Annual gathering of psychedelic researchers, therapists, and practitioners featuring keynote speakers and workshops on DMT research breakthroughs.', '2026-01-15', 'public', 'Denver, Colorado', 'Psychedelics Today', 'https://psychedelicstoday.com', true, NULL),
('MAPS Psychedelic Science Summit', 'Multi-day symposium covering clinical trials, harm reduction, and therapeutic applications of psychedelics including DMT and psilocybin studies.', '2025-06-20', 'public', 'San Francisco, CA', 'MAPS', 'https://maps.org', true, NULL),
('DMT Research Workshop - Imperial College', 'Intensive workshop on DMT neuroscience, phenomenology, and clinical research methodologies led by leading researchers.', '2025-09-10', 'workshop', 'London, UK', 'Imperial College London', 'https://imperial.ac.uk', true, NULL),
('Horizons: Perspectives on Psychedelics', 'Annual NYC conference exploring psychedelic science, policy, and culture with presentations on DMT and 5-MeO-DMT research.', '2025-10-18', 'public', 'New York, NY', 'Horizons', 'https://horizons.nyc', true, NULL),
('Breaking Convention 2026', 'Multidisciplinary conference on psychedelic research bringing together scientists, artists, and advocates discussing DMT protocols.', '2026-07-03', 'public', 'London, UK', 'Breaking Convention', 'https://breakingconvention.co.uk', true, NULL);

-- Seed sample clinical trials (3 trials)
INSERT INTO public.clinical_trials (title, description, institution, principal_investigator, start_date, end_date, status, trial_registry_id, url, is_approved, submitted_by) VALUES
('Phase II Study of DMT-Assisted Therapy for Treatment-Resistant Depression', 'Randomized, double-blind, placebo-controlled trial evaluating safety and efficacy of N,N-DMT with psychological support in patients with major depressive disorder.', 'Johns Hopkins University', 'Dr. Roland Griffiths', '2025-03-01', '2027-12-31', 'recruiting', 'NCT05123456', 'https://clinicaltrials.gov/study/NCT05123456', true, NULL),
('Psilocybin vs Escitalopram for Major Depressive Disorder', 'Comparative effectiveness trial examining psilocybin-assisted therapy against standard SSRI treatment in moderate to severe depression.', 'Imperial College London', 'Dr. Robin Carhart-Harris', '2024-01-15', '2026-06-30', 'active', 'NCT04987654', 'https://clinicaltrials.gov/study/NCT04987654', true, NULL),
('5-MeO-DMT Safety and Tolerability Study', 'Phase I dose-escalation study assessing pharmacokinetics, safety profile, and subjective effects of synthetic 5-MeO-DMT in healthy volunteers.', 'University of California San Francisco', 'Dr. Alan Davis', '2025-08-01', '2026-12-31', 'planned', 'NCT05234567', 'https://clinicaltrials.gov/study/NCT05234567', true, NULL);

-- Seed sample retreats (4 retreats)
INSERT INTO public.retreats (name, description, location, country, tags, website_url, contact_email, is_approved, submitted_by) VALUES
('Synthesis Institute', 'Legal psilocybin retreat center offering guided ceremonial experiences with trained facilitators, integration support, and comprehensive screening protocols.', 'Amsterdam', 'Netherlands', ARRAY['psilocybin', 'legal', 'clinical', 'integration'], 'https://synthesisretreat.com', 'info@synthesisretreat.com', true, NULL),
('Temple of the Way of Light', 'Traditional Shipibo ayahuasca retreat in the Peruvian Amazon offering 9-12 day immersive programs with indigenous healers and integration circles.', 'Iquitos', 'Peru', ARRAY['ayahuasca', 'traditional', 'shamanic', 'jungle'], 'https://templeofthewayoflight.org', 'info@templeofthewayoflight.org', true, NULL),
('MycoMeditations', 'Psilocybin retreat in Jamaica featuring small-group ceremonial sessions, medical screening, psychological preparation, and post-retreat integration.', 'Treasure Beach', 'Jamaica', ARRAY['psilocybin', 'legal', 'group', 'beachfront'], 'https://mycomeditations.com', 'info@mycomeditations.com', true, NULL),
('Beckley Retreats', 'Research-backed psychedelic wellness retreats combining psilocybin ceremonies with mindfulness practices, neuroscience education, and long-term integration support.', 'Multiple Locations', 'Netherlands/Jamaica', ARRAY['psilocybin', 'research-backed', 'wellness', 'science'], 'https://beckleyretreats.com', 'info@beckleyretreats.com', true, NULL);